### ISSUE TITLE
Error code: 522 - Since  GeForce Experience 2.1.2.0

### ISSUE THREAD

**Issue by fishxz** [moonlight-stream/moonlight-embedded#44]
Since i switched to  GeForce Experience 2.1.2.0 i always get this error:

GFE error: Streaming session has failed due to a game management error. (Error code: 522)

I already upgraded to Limelight Embedded 1.1

**Comment by PcInfamy** [comment]
Im getting this error:

root@raspberrypi:/home/pi# java -jar limelight-pi.jar 192.168.1.22
Starting app
com.limelight.nvstream.http.GfeHttpResponseException: GFE error: Streaming session has failed due to a game management error. (Error code: 522)
        at com.limelight.nvstream.http.NvHTTP.verifyResponseStatus(Unknown Source)
        at com.limelight.nvstream.http.NvHTTP.getXmlString(Unknown Source)
        at com.limelight.nvstream.http.NvHTTP.getXmlString(Unknown Source)
        at com.limelight.nvstream.http.PairingManager.getPairState(Unknown Source)
        at com.limelight.nvstream.http.NvHTTP.getPairState(Unknown Source)
        at com.limelight.nvstream.NvConnection.startApp(Unknown Source)
        at com.limelight.nvstream.NvConnection.establishConnection(Unknown Source)
        at com.limelight.nvstream.NvConnection.access$300(Unknown Source)
        at com.limelight.nvstream.NvConnection$1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:744)
GFE error: Streaming session has failed due to a game management error. (Error code: 522)
Connection Error Starting app failed
